# Generated by Django 5.1.5 on 2025-03-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturehall',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
