# Generated by Django 5.1.5 on 2025-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_lecturehall_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmittedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='lecturehall',
            name='non_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
