# Generated by Django 5.1.5 on 2025-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('timetable', '0003_omitteddays_lecturehall_non_ac_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='ac_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='projector_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slots',
            field=models.ManyToManyField(to='timetable.timeslot'),
        ),
    ]
