# Generated by Django 5.1.5 on 2025-03-25 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_time_slot_booking_ac_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_tokens',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('non-academic', 'Non-Academic')], default='non-academic', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='decision_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
